name: Python build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          python -m unittest
      - name: Build
        run: |
          pyinstaller optimizer.py
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: geat_optimizer
          path: dist